# Generated by Django 5.1.5 on 2025-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0002_news_alter_buyer_balance'),
    ]

    operations = [

    ]
